# Generated by Django 4.2.6 on 2023-10-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_metodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMetodo', models.CharField(max_length=50)),
            ],
        ),
    ]
