# Generated by Django 4.2.6 on 2023-10-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_tb_metodopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_metodoPago',
        ),
    ]
