# Generated by Django 4.2.6 on 2023-10-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_delete_tb_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
